default_install_hook_types: [commit-msg, pre-commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
        stages: [pre-commit]
      - id: trailing-whitespace
        stages: [pre-commit]
      - id: check-json
        stages: [pre-commit]
      - id: check-yaml
        stages: [pre-commit]
        args:
          - --unsafe
      - id: check-symlinks
        stages: [pre-commit]
      - id: check-added-large-files
        stages: [pre-commit]
        args:
          - --maxkb=15000
      - id: detect-private-key
        stages: [pre-commit]

  - repo: https://github.com/antonbabenko/pre-commit-terraform.git
    rev: v1.96.2
    hooks:
      - id: terraform_fmt
        stages: [pre-commit]
      #  - id: terraform_docs
      #   stages: [pre-commit]
      #   args:
      #     - --args=--config=.config/terraform-docs.yml
      #     - --hook-config=--use-standard-markers=true
      #   exclude: "^modules|^example|^tools"
      - id: terraform_validate
        stages: [pre-commit]
        exclude: ^examples
        args:
          - --tf-init-args=-upgrade
          - --hook-config=--retry-once-with-cleanup=true
      # - id: terraform_tflint
      #   stages: [pre-commit]
      #   exclude: ^examples
      #   args:
      #     - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
      # - id: terraform_trivy
      #   stages: [pre-commit]
      - id: terraform_checkov

  # - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  #   rev: v9.18.0
  #   hooks:
  #     - id: commitlint
  #       stages: [commit-msg]
  #       additional_dependencies: ["@commitlint/config-conventional"]
